# Numpy

 

### Numpy stands for Numeric Python, using in lib we perform Numeric Operations.

In [2]:
import numpy as np

In [3]:
a = 10
b = 20

a+b   # here, we have just used the opertor

30

In [4]:
sum(a,b)  #erroe bcz we can't use functions directly on veriables,we will use []

TypeError: 'int' object is not iterable

In [5]:
sum([a,b])

30

In [6]:
np.add(a,b)   

30

In [7]:
np.subtract(a,b)   

-10

# Numpy consist of bulitin data structures:

In [8]:

# 1. Array: (1D,2D,3D......nD) 

# 2. Matrix: (2 Dementional) --> rows & columns

# 1 & 2 are only the data structures in numpy package but assumes 2 more:

# 3. Scalar: 
#           singular value, eg- 1,2,3,4...

# 4. Vector: (1 Dementional)
#     a. row vector: [1,2,3,4...]
#     b. column vector : 
#                         [1,
#                          2,
#                          3] 


In [9]:
# !pip install numpy  -- used install any package/lib

In [10]:
# Scalar

a = np.array(10)
a

array(10)

In [11]:
type(a)    # checking data type

numpy.ndarray

In [12]:
# Row Vector


b = np.array([1,2,3,4])   # it is mandatory to use [] when we put more then one value in array
b

array([1, 2, 3, 4])

In [13]:
b.ndim     # checking no. of dimensions

1

In [14]:
# In numpy we can't bulid column vector

## MATRIX


Default data structure of Numpy

In [17]:
c = np.matrix([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [ ]:
# [[1,2,3],[4,5,6]]

# [1,2,3] is 1st D and [4,5,6] is 2nd D

In [16]:
type(c)

numpy.matrix

In [17]:
c.ndim

2

In [18]:
d = np.array([[0,1,0],[1,1,1]])
d

array([[0, 1, 0],
       [1, 1, 1]])

In [19]:
type(d)

numpy.ndarray

In [20]:
d.ndim

2

In [21]:
# 2D array & 2D matrix are same just a d/f ways to write the same

In [22]:
# 3D Array

e = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
e

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [23]:
e.ndim

3

## Shape

(no. of rows,no. of columns)

In [26]:
d

array([[0, 1, 0],
       [1, 1, 1]])

In [28]:
d.shape     #(2 rows, 3 columns)

(2, 3)

## Size

count no. of elements present in the array

In [29]:
d.size

6