# Random

### --> 1. Sample

* It gives random values b/w 0 to 1
* These values changes at every excution
* It requires extra one perenthesis, i.e () --> (())

In [2]:
import numpy as np

In [6]:
np.random.sample((3,3))        # ((no. of rows, no. of columns))

array([[0.36695785, 0.98285236, 0.72949376],
       [0.33636966, 0.01575862, 0.05817561],
       [0.5930835 , 0.00459059, 0.06445593]])

In [8]:
np.random.sample((3,5))        # ((no. of rows, no. of columns))

array([[0.57592256, 0.78611239, 0.9363667 , 0.34973079, 0.06741574],
       [0.03835636, 0.16199726, 0.22317782, 0.00380333, 0.78862477],
       [0.96074525, 0.09795427, 0.40685531, 0.21281105, 0.27185792]])

### --> 2. Seed

* It is used to freeze the randomness of sample
* Just fix/lock the random values


In [12]:
np.random.seed(101)    #(just provide any no., it has no significance on the output)

np.random.sample((3,3))        

array([[0.51639863, 0.57066759, 0.02847423],
       [0.17152166, 0.68527698, 0.83389686],
       [0.30696622, 0.89361308, 0.72154386]])

### --> 3. Randn

* It gives values in Normal Distribution
* Don't need extra perenthesis
* These values changes at every excution, Use SEED to lock the values

In [20]:
a = np.random.randn(3,3)
a

array([[-0.3464185 ,  0.14702677, -0.47944804],
       [ 0.55876941,  1.02481028, -0.92587426],
       [ 1.86286414, -1.13381716,  0.61047791]])

### --> 4. Randint

* It gives values in the speficied range
* random.randint(strt point, end point, (D of array))
* These values changes at every excution, Use SEED to lock the values

In [21]:
b = np.random.randint(10,100,(3,3))
b

array([[56, 13, 56],
       [39, 96, 31],
       [31, 91, 33]])

# Zeros

* Fills the array with 0
* It requires extra one perenthesis, i.e () --> (())

In [23]:
np.zeros((3,3))    # by default it gives float values

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
# If I want to change the datatype:

np.zeros((3,3),dtype=int) 

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

# Ones


* Fills the array with the 1
* It requires extra one perenthesis, i.e () --> (())

In [25]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# Full

* Fills the array with the specified/particular constant
* It requires extra one perenthesis, i.e () --> (())
* np.full((Shape), specified no.)

In [29]:
np.full((3,3), 99)

array([[99, 99, 99],
       [99, 99, 99],
       [99, 99, 99]])

# Eye

* It gives no. 1 Diagonally & fill rest positions with 0


In [31]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [33]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Arange

* Same as range function


In [35]:
np.arange(10)       # End Position

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.arange(10,20)       # Start Position, End Position

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [37]:
np.arange(10,20,2)       # Start Position, End Position, Interval

array([10, 12, 14, 16, 18])

# Linspace

* It equally seprates the values from start position & end position 
* It always includes start position & end position in output

In [42]:
np.linspace(1,9,3)   # Start Position, End Position, No. of values to be print

array([1., 5., 9.])

In [43]:
np.linspace(10,100,10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])