# Convert 1D Array to 2D Array

In [2]:
import numpy as np

### Reshape

* Converts the 1D array into specified D array

In [4]:
a = np.arange(10,20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [8]:
a.ndim

1

In [11]:
b = a.reshape(2,5)
b

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [12]:
b = a.reshape(5,2)
b

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [14]:
b.ndim

2

# Convert nD Array into 1D Array

### Ravel

* Used to convert nD array into 1D array

In [17]:
c = b.ravel()
c

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [18]:
c.ndim

1

## Accessing Values from Arrays - Indexing & Slicing

In [3]:
a = np.random.randint(10,100,(3,5))
a

array([[27, 22, 39, 67, 88],
       [90, 35, 97, 25, 36],
       [25, 22, 19, 33, 35]])

Syntax for accessing 2D array:

a[ : , : ]

a[rows,columns]

a[ SP:EP, SP:EP]

* SP -> Start Position
* EP -> End Position

-> In Indexing End Position is always Excluded

In [4]:
a[:]  # accesses all array

array([[27, 22, 39, 67, 88],
       [90, 35, 97, 25, 36],
       [25, 22, 19, 33, 35]])

In [5]:
a[0]  # accesses 1st row

array([27, 22, 39, 67, 88])

In [6]:
a[2] # accesses 3rd row

array([25, 22, 19, 33, 35])

In [7]:
# Rows can be access sperately but columns can't be access sperately

In [8]:
# I want access all the elements of 3rd column


a[:,2]

array([39, 97, 19])

In [9]:
a

array([[27, 22, 39, 67, 88],
       [90, 35, 97, 25, 36],
       [25, 22, 19, 33, 35]])

In [10]:
# access all the rows expect last row


a[:2,:]

array([[27, 22, 39, 67, 88],
       [90, 35, 97, 25, 36]])

In [11]:
a[0:2,:]

array([[27, 22, 39, 67, 88],
       [90, 35, 97, 25, 36]])

In [12]:
# access the 3rd,4th & 5th column

a[:,2:]

array([[39, 67, 88],
       [97, 25, 36],
       [19, 33, 35]])

In [13]:
# Access 1st two column

a[:,:2]

array([[27, 22],
       [90, 35],
       [25, 22]])

In [14]:
a

array([[27, 22, 39, 67, 88],
       [90, 35, 97, 25, 36],
       [25, 22, 19, 33, 35]])

In [15]:
# access only 11,78,39,28


a[1:,2:4]

array([[97, 25],
       [19, 33]])

## Non-Sequential Accessing

In [19]:
a

array([[27, 22, 39, 67, 88],
       [90, 35, 97, 25, 36],
       [25, 22, 19, 33, 35]])

In [16]:
# access only 1st row and last row

a[[0,2],:]                 #   [[1st row, 2nd row],all columns]

array([[27, 22, 39, 67, 88],
       [25, 22, 19, 33, 35]])

In [17]:
# access only 2nd column and last column

a[:,[2,4]]                 

array([[39, 88],
       [97, 36],
       [19, 35]])

In [24]:
# access paritcular values for both row and colum


a[[0,2],[1,4]]

array([22, 35])

## Accessing Particular Element

In [31]:
a

array([[12, 81, 23, 67, 88],
       [49, 83, 11, 78, 46],
       [24, 52, 39, 28, 71]])

In [33]:
# Access the element 83


a[1,1]       #   [element's row position, element's column position]

83

In [34]:
# Access the element 28


a[2,3]

28

## Boolean Indexing

In [37]:

b = list(range(20))
b

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [38]:
# I want all those values from list 'b' which are devisible by 4


b % 4 ==0      

# so, it gives error bcz we can't perform this task directly, 

# but we can perform this task with the help of for loop, while loop, lambda & list comprehansion

TypeError: unsupported operand type(s) for %: 'list' and 'int'

In [39]:
# But in NUMPY we can form this task directly

a

array([[12, 81, 23, 67, 88],
       [49, 83, 11, 78, 46],
       [24, 52, 39, 28, 71]])

In [40]:
a % 4 ==0     # It gives output in boolean 

array([[ True, False, False, False,  True],
       [False, False, False, False, False],
       [ True,  True, False,  True, False]])

In [41]:
# So, we don't boolean and need exact values then

a[a % 4 ==0]

array([12, 88, 24, 52, 28])