# Operations in Arrays

### Types of Operations:

* Arithmetic & Element-Wise Operations
* Aggregation Operation
* Axis-Wise Operations
* Stacking Operation

In [2]:
b = list(range(10))
b

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
# I want to add 10 to every element of list

b + 10         # without loop, lamda, list comp.,etc we can't do

TypeError: can only concatenate list (not "int") to list

In [6]:
[i+10 for i in b]    # In this way can do but in the numpy we can do it directly

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [1]:
import numpy as np

In [3]:
a = np.random.randint(10,100,(3,5))
a

array([[38, 14, 12, 43, 42],
       [37, 25, 85, 87, 49],
       [47, 22, 56, 11, 60]])

In [4]:
a+10000

array([[10038, 10014, 10012, 10043, 10042],
       [10037, 10025, 10085, 10087, 10049],
       [10047, 10022, 10056, 10011, 10060]])

In [5]:
a/100

array([[0.38, 0.14, 0.12, 0.43, 0.42],
       [0.37, 0.25, 0.85, 0.87, 0.49],
       [0.47, 0.22, 0.56, 0.11, 0.6 ]])

In [6]:
a//2

array([[19,  7,  6, 21, 21],
       [18, 12, 42, 43, 24],
       [23, 11, 28,  5, 30]], dtype=int32)

In [7]:
a%2

array([[0, 0, 0, 1, 0],
       [1, 1, 1, 1, 1],
       [1, 0, 0, 1, 0]], dtype=int32)

In [8]:
10/5

2.0

In [9]:
10//5

2

## 1. Arithmetic & Element-Wise Operations

In [10]:
# We can use directly operators(used above) or numpy functions

In [11]:
np.add(a,10000)

array([[10038, 10014, 10012, 10043, 10042],
       [10037, 10025, 10085, 10087, 10049],
       [10047, 10022, 10056, 10011, 10060]])

In [12]:
np.subtract(a,10)

array([[28,  4,  2, 33, 32],
       [27, 15, 75, 77, 39],
       [37, 12, 46,  1, 50]])

In [13]:
np.multiply(a,2)

array([[ 76,  28,  24,  86,  84],
       [ 74,  50, 170, 174,  98],
       [ 94,  44, 112,  22, 120]])

In [14]:
np.divide(a,10)

array([[3.8, 1.4, 1.2, 4.3, 4.2],
       [3.7, 2.5, 8.5, 8.7, 4.9],
       [4.7, 2.2, 5.6, 1.1, 6. ]])

In [15]:
np.sqrt(a)

array([[6.164414  , 3.74165739, 3.46410162, 6.55743852, 6.4807407 ],
       [6.08276253, 5.        , 9.21954446, 9.32737905, 7.        ],
       [6.8556546 , 4.69041576, 7.48331477, 3.31662479, 7.74596669]])

## 2. Aggregation Operation

In [16]:
a

array([[38, 14, 12, 43, 42],
       [37, 25, 85, 87, 49],
       [47, 22, 56, 11, 60]])

In [17]:
np.sum(a)

628

In [18]:
np.min(a)

11

In [19]:
np.max(a)

87

In [20]:
np.std(a)

22.867346928656932

In [21]:
np.var(a)

522.9155555555556

In [22]:
[a % 4 == 0]

[array([[False, False,  True, False, False],
        [False, False, False, False, False],
        [False, False,  True, False,  True]])]

In [23]:
a[a % 4 == 0]

array([12, 56, 60])

In [24]:
a[a % 4 == 0].sum()

128

## 3. Axis-Wise Operations

In [25]:
a

array([[38, 14, 12, 43, 42],
       [37, 25, 85, 87, 49],
       [47, 22, 56, 11, 60]])

In [26]:
# I want column wise sum

a.sum(axis = 0)         # 0--> columns & 1 --> Rows

array([122,  61, 153, 141, 151])

In [27]:
# I want row wise sum

a.sum(axis = 1)

array([149, 283, 196])

In [28]:
a.min(axis=1)

array([12, 25, 11])

In [29]:
a.mean(axis=0)

array([40.66666667, 20.33333333, 51.        , 47.        , 50.33333333])

In [31]:
# now I want only 2 digit decimal for above mean

np.around(a.mean(axis=0),2)

array([40.67, 20.33, 51.  , 47.  , 50.33])

## 4. Concatenation, Stack & Split


### Concatenation

In [33]:
b = np.array([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

In [42]:
c = np.array([[5,6]])
c

array([[5, 6]])

In [35]:
# I want to add c to array b

b+c

array([[ 6,  8],
       [ 8, 10]])

In [43]:
b.shape

(2, 2)

In [44]:
c.shape

(1, 2)

In [45]:
# I want add c as a new row to the array b

np.concatenate([b,c])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [46]:
# so, be default it takes axis=0, means added the c as a new row


In [48]:
# I want to add c as a new column to the array b

np.concatenate([b,c], axis=1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [49]:
# It shows error bcz, shape(dimension) of both array is not same

# as c has 1 row & 2 columns, b has 2rows and 2columns. To add c we need 2 rows(use transpose to make it into 2rows)

In [53]:
c.T

array([[5],
       [6]])

In [55]:
c.T.shape

(2, 1)

In [57]:
np.concatenate([b,c.T],axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [58]:
# NOTE: When we need add/merge array as row ---> columns of both array must be same
#       When we need add/merge array as column ---> rows of both array must be same

### Stack

* Same as concatenate

In [59]:
b

array([[1, 2],
       [3, 4]])

In [60]:
c

array([[5, 6]])

In [62]:
# Used to add as a row

np.vstack([b,c])      # vstack --> Vertical Stack

array([[1, 2],
       [3, 4],
       [5, 6]])

In [64]:
# Used to add as a column

np.hstack([b,c.T])  # hstack --> Horizonal Stack

array([[1, 2, 5],
       [3, 4, 6]])

### Split

In [65]:
a

array([[38, 14, 12, 43, 42],
       [37, 25, 85, 87, 49],
       [47, 22, 56, 11, 60]])

In [73]:
# hspilt --> spilt the existing array into equal no. of columns in new arrays

In [74]:
np.hsplit(a,5)

[array([[38],
        [37],
        [47]]),
 array([[14],
        [25],
        [22]]),
 array([[12],
        [85],
        [56]]),
 array([[43],
        [87],
        [11]]),
 array([[42],
        [49],
        [60]])]

In [75]:
# vsplit --> spilt the existing array into equal no. of rows in new arrays

In [76]:
np.vsplit(a,3)

[array([[38, 14, 12, 43, 42]]),
 array([[37, 25, 85, 87, 49]]),
 array([[47, 22, 56, 11, 60]])]

In [77]:
# If I want to access new arrays sperately and assign some variable to each 


first_row = np.vsplit(a,3)[0]

second_row = np.vsplit(a,3)[1]

third_row = np.vsplit(a,3)[2]

In [79]:
first_row 

array([[38, 14, 12, 43, 42]])

In [80]:
second_row

array([[37, 25, 85, 87, 49]])

In [81]:
third_row

array([[47, 22, 56, 11, 60]])